### ISSUE TITLE
Some help for support install from pre-build binaries

### ISSUE THREAD

**Issue by gucong3000** [Dezeiraud/bsdiff-nodejs#11]
We need to configuration NODE_PRE_GYP_GITHUB_TOKEN environment variable: 
https://www.npmjs.com/package/node-pre-gyp-github#configuration

`node-pre-gyp-github` require `NODE_PRE_GYP_GITHUB_TOKEN` to publish binaries
We can setup here:
https://ci.appveyor.com/project/Brouilles/bsdiff-nodejs/settings/environment
https://travis-ci.org/Dezeiraud/bsdiff-nodejs/settings
![image](https://cloud.githubusercontent.com/assets/1171691/24574053/a3a161f4-16bf-11e7-8a97-5d2b0e74b63f.png)

Once you've configured these, CIs will automatically upload the pre-built files to release each time you [create a new release version](https://github.com/Dezeiraud/bsdiff-nodejs/releases/new).

**Comment by Brouilles** [comment]
Hi,
Thanks for the issue. I have done the configuration but, as you could see, the releases are not updated since the version 2.0.0 because I have an issue with Github when I want to create a new release, I get "Oups 500" error ... For weeks.

I try to contact the Github support (same problem with others web browsers and computer).
Thanks.
